name       : freedroidrpg
version    : 0.16
release    : 1
source     :
    - ftp://ftp.osuosl.org/pub/freedroid/freedroidRPG-0.16/freedroidRPG-0.16.tar.gz : c11f28b69eed3e8e40528442d9e840847502ccd4d3d95d3f8182abc2b3b18135
license    : GPL-2.0
component  : games.rpg
summary    : FreeDroid RPG - The game tells the story of a world destroyed by a conflict between robots and their human masters
description: |
    FreeDroid RPG - The game tells the story of a world destroyed by a conflict between robots and their human masters.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(sdl)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_ttf)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
