name       : freedroidrpg
version    : 0.16.1
release    : 7
source     :
    - https://gitlab.com/freedroid/freedroid-src/-/archive/0.16.1/freedroid-src-0.16.1.tar.bz2 : 652d8f94fef0f2269983e1b13298f45deb57fbfb8e02c62d8d61d2ed7554fc0c
license    : GPL-2.0-or-later
component  : games.rpg
summary    : FreeDroid RPG - The game tells the story of a world destroyed by a conflict between robots and their human masters
description: |
    FreeDroid RPG - The game tells the story of a world destroyed by a conflict between robots and their human masters.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua-5.1)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_ttf)
    - pkgconfig(vorbis)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
