name       : freedroidrpg
version    : '1.0'
release    : 9
source     :
    - https://gitlab.com/freedroid/freedroid-src/-/archive/1.0/freedroid-src-1.0.tar.gz : 5b6544ec2d1acc1818a9d88d78148b9792ae63841f5a38702e47b4445264bee9
homepage   : https://www.freedroid.org/
license    : GPL-2.0-or-later
component  : games.rpg
summary    : Isometric 3D role playing game taking place in the future, on Earth
description: |
    The game tells the story of a world destroyed by a conflict between robots and their human masters. Play as Tux in a quest to save the world from the murderous rebel bots who know no mercy. You get to choose which path you wish to follow, and freedom of choice is everywhere in the game.
builddeps  :
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_ttf)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua-5.1)
    - pkgconfig(vorbis)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
