name       : freedroidrpg
version    : 0.16.1
release    : 2
source     :
    - http://ftp.osuosl.org/pub/freedroid/freedroidRPG-0.16/freedroidRPG-0.16.1.tar.gz : 426df175034b12095e7498fd80c907e507667c960ee1da331d9e5566d1b09358
license    : GPL-2.0
component  : games.rpg
summary    : FreeDroid RPG - The game tells the story of a world destroyed by a conflict between robots and their human masters
description: |
    FreeDroid RPG - The game tells the story of a world destroyed by a conflict between robots and their human masters.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(sdl)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_ttf)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
